name: Laravel-Siskeu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: siskeu
          MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Wait for MySQL to be ready
      run: sleep 15

    - name: Update .env for MySQL
      run: |
        sed -i 's/APP_NAME=.*/APP_NAME=Laravel/' .env
        sed -i 's/APP_ENV=.*/APP_ENV=local/' .env
        sed -i 's/APP_DEBUG=.*/APP_DEBUG=true/' .env
        sed -i 's/APP_TIMEZONE=.*/APP_TIMEZONE=UTC/' .env
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=siskeu/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env
        sed -i 's/SESSION_DRIVER=.*/SESSION_DRIVER=database/' .env
        sed -i 's/QUEUE_CONNECTION=.*/QUEUE_CONNECTION=database/' .env
        sed -i 's/CACHE_STORE=.*/CACHE_STORE=database/' .env
        sed -i 's/MAIL_MAILER=.*/MAIL_MAILER=log/' .env

    - name: Install Dependencies
      run: 
        composer update
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: siskeu
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan migrate

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: siskeu
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan test
